name: build docker image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: ghcr.io/jonohill
  DOCKER_REPO: gh-runner

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr
        uses: docker/login-action@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull upstream
        id: pull_upstream
        run: |
          source version.txt

          # nestybox images
          git clone https://github.com/nestybox/dockerfiles.git nesty
          cd nesty
          dockerfile_path="ubuntu-focal-systemd-docker/Dockerfile"
          sed -i \
            "s|^FROM nestybox/ubuntu-focal-systemd:latest|FROM $DOCKER_REGISTRY/nestybox/ubuntu-focal-systemd:${{ github.run_id }}\nARG TARGETPLATFORM|g" \
            "$dockerfile_path"
          sed -i \
            's~amd64~$(echo $TARGETPLATFORM | sed "s|linux/||g")~g' \
            "$dockerfile_path"
          cd -

          # gh-runner image
          git clone https://github.com/PasseiDireto/gh-runner.git gh-runner
          cd gh-runner
          git checkout "$UPSTREAM_VERSION"
          sed -i \
            "s|^FROM nestybox/ubuntu-focal-systemd-docker|FROM $DOCKER_REGISTRY/nestybox/ubuntu-focal-systemd-docker:${{ github.run_id }}|g" \
            Dockerfile
          sed -i \
            's|ARG TARGETPLATFORM=amd64|ARG TARGETPLATFORM|g' \
            Dockerfile
          cd -

          echo "::set-output name=VERSION::$UPSTREAM_VERSION"

      - name: Build ubuntu-focal-systemd
        id: docker_build_ubuntu-focal-systemd
        uses: docker/build-push-action@v5
        with:
          context: nesty/ubuntu-focal-systemd
          file: ./nesty/ubuntu-focal-systemd/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max          
          tags: "${{ env.DOCKER_REGISTRY}}/nestybox/ubuntu-focal-systemd:${{ github.run_id }}"

      - name: Build ubuntu-focal-systemd-docker
        id: docker_build_ubuntu-focal-systemd-docker
        uses: docker/build-push-action@v5
        with:
          context: nesty/ubuntu-focal-systemd-docker
          file: ./nesty/ubuntu-focal-systemd-docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max          
          tags: "${{ env.DOCKER_REGISTRY}}/nestybox/ubuntu-focal-systemd-docker:${{ github.run_id }}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: gh-runner
          file: ./gh-runner/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max          
          tags: "${{ env.DOCKER_REGISTRY}}/${{ env.DOCKER_REPO }}:${{ steps.pull_upstream.outputs.VERSION }}"
