name: build docker image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  DOCKER_REPO: ghcr.io/jonohill/gh-runner

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr
        uses: docker/login-action@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull upstream
        id: pull_upstream
        run: |
          source version.txt

          git clone https://github.com/PasseiDireto/gh-runner.git gh-runner
          cd gh-runner
          git checkout "$UPSTREAM_VERSION"
          cd -

          echo "::set-output name=VERSION::$UPSTREAM_VERSION"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: gh-runner
          file: ./gh-runner/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max          
          tags: "${{ env.DOCKER_REPO }}:${{ steps.pull_upstream.outputs.VERSION }}"
